from dataclasses import dataclass, fields

@dataclass
class Game:
    website_id: int
    name: str
    description: str
    price: float
    image_url: str
    has_stock: bool
    url: str
    categories: list[str] | None = None
    id: int | None = None
    sale_price: float | None = None

    def to_create_db_dict(self) -> dict:
        """Convert the Game instance to a dictionary for database insertion. 
        
        All entity fields are included except 'id', which is auto-generated by the database.
        """

        return {
            "website_id": self.website_id,
            "name": self.name,
            "description": self.description,
            "price": self.price,
            "categories": self.categories,
            "sale_price": self.sale_price,
            "image_url": self.image_url,
            "has_stock": self.has_stock,
            "url": self.url,
        }
    
    def to_update_db_dict(self) -> dict:
        """Convert the Game instance to a dictionary for database update.
        
        The id field is necessary to identify the record to update.

        The fields that can be updated are:
            - description
            - price
            - categories
            - sale_price
            - image_url
            - has_stock
        """

        return {
            "id": self.id,
            "description": self.description,
            "price": self.price,
            "categories": self.categories,
            "sale_price": self.sale_price,
            "image_url": self.image_url,
            "has_stock": self.has_stock,
        }
    
    def set_id(self, id: int) -> None:
        """Set the ID of the Game instance if it is not already set.
        
        The ID that is being set should come from the database after insertion.
        """

        if self.id:
            return
        self.id = id

    def to_row(self) -> list:
        """Convert the Game instance to a list representing a row for CSV export.
        
        Fields to include:
        - Game name
        - Game price
        - The stock status is represented as "In Stock" or "Out of Stock"
        - Game URL
        """

        has_stock_string = "In Stock" if self.has_stock else "Out of Stock"
        return [
            self.name,
            self.price,
            has_stock_string,
            self.url,
        ]
        
    @classmethod
    def get_fields_name(cls) -> list[str]:
        """Get the list of field names of the Game dataclass.
        
        This is used for CSV header creation.

        Fields included are:
        - categories (will be added by the CSV writer)
        - name
        - price
        - has_stock
        - url
        """

        return [
            "categories",
            "name",
            "price",
            "has_stock",
            "url",
        ]